version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2
    container_name: elasticsearch
    expose:
     - 9200
    restart: unless-stopped
    environment:
    - "transport.host=127.0.0.1"
    - "xpack.security.enabled=false"
    ports:
      - 9200:9200
  server:
    build: ./server
    volumes:
      - C:\Users\jeana\Documents\belleSoupe\server:/usr/src/app/server
    ports:
       - 8080:8080
    depends_on:
       - elasticsearch
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/:/usr/src/app/client/
